import os
from datetime import datetime

def generate_html_report(report_text, png_paths=None, output_path="reports/evalforge_report.html"):
    """
    Wraps the CLI output and any generated PNGs into a clean, shareable HTML file.
    Because executives love opening things in their browsers :)
    
    Args:
        report_text (str): The markdown text string from report_card.py.
        png_paths (list): List of file paths to the generated charts.
        output_path (str): The destination path for the HTML file.
        
    Returns:
        str: The absolute path to the generated HTML report.
    """
    if png_paths is None:
        png_paths = []
        
    # Basic CSS inline for zero-dependency styling
    css = """
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; background-color: #f9f9f9; }
        .container { background-color: #fff; padding: 40px; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
        h1, h2, h3, h4 { color: #2c3e50; }
        pre { background-color: #2c3e50; color: #ecf0f1; padding: 20px; border-radius: 6px; overflow-x: auto; white-space: pre-wrap; word-wrap: break-word;}
        .images { display: flex; flex-wrap: wrap; gap: 20px; margin-top: 30px; }
        .image-card { flex: 1; min-width: 300px; background: #fff; border: 1px solid #eee; padding: 10px; border-radius: 8px; text-align: center; box-shadow: 0 2px 4px rgba(0,0,0,0.05);}
        img { max-width: 100%; height: auto; border-radius: 4px; }
        .footer { margin-top: 40px; font-size: 0.8em; color: #7f8c8d; text-align: center;}
    </style>
    """
    
    # We cheat slightly by putting the markdown inside a nicely styled <pre> block
    # so we don't have to force users to pip install markdown.
    html = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>EvalForge Diagnostic Report</title>
        {css}
    </head>
    <body>
        <div class="container">
            <h2>🛡️ EvalForge Diagnostic Report</h2>
            <p>Generated on: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>
            
            <pre>{report_text}</pre>
            
            <h3>Visual Evidence</h3>
    """
    
    if len(png_paths) > 0:
        html += '<div class="images">'
        for path in png_paths:
            # We assume the png paths are relative to where the HTML is opened,
            # so we just use the basename if they are all dumped in 'reports/'
            filename = os.path.basename(path)
            html += f"""
            <div class="image-card">
                <p><strong>{filename}</strong></p>
                <img src="{filename}" alt="{filename}">
            </div>
            """
        html += '</div>'
    else:
        html += "<p>No visualizations were generated for this run.</p>"
        
    html += """
        </div>
        <div class="footer">
            <p>Generated by EvalForge • "Accuracy is a lie. Bias is a lawsuit. EvalForge sees both."</p>
        </div>
    </body>
    </html>
    """
    
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)
        
    return os.path.abspath(output_path)
